baekjoon/boj_12851_crystal.py

1. 최단거리에서 bfs를 떠올렸다가, 그 거리가 계산되는 모든 경우의 수를 반환하라고 해서 dfs로 풀었다. 
2. 현재 위치마다 +1, -1 *2 를 선택하여 나아가는 방법을 다 고려해서 시도 했음
3. 당연히.. 깊이 문제로 코드가 실행되지 않음 (가지치기를 통해 면회해보려 했으나 실패)
모든 경우의 수를 구할 땐 방문 여부를 따지는 bfs로는 구현할 수 없다고 생각했는데, 이런 문제에도 조건을 잘 구성하여 재방문 가능한 bfs를 구현할 수 있음을 깨달음.
```python
for next_point in [cur_point + 1, cur_point - 1, cur_point * 2]:
if 0 <= next_point < 100_001:
if distance[next_point] == 0 or distance[cur_point] + 1 == distance[next_point]:
```

[FEAT] #1 최수정

---

baekjoon/boj_1283_crystyal.py

생각보다 구현이 까다로웠다. 그 이유는 조건이 서로 연관 되어 있었기 때문이다.
단어의 첫 글자에서 단축키가 안 나오면 뒤의 글자에서 단축키를 찾아야 하는 로직이 그 예시이다.  
- IF 문을 안 쓰고 최대한 함수형 프로그래밍으로 풀어보려 했다.  : 점점 코드가 꼬여 결국은 IF를 사용함
- dictionary 자료를 이용하여 혹여나 알파벳 길이가 길어져도 기사용 조회 시, 짧은 시간으로 조회 가능
`.upper()`를 사용해서 모든 문자를 대문자화 할 수 있다.

[FEAT] #2 최수정

---

baekjoon/boj_5525_hoon.md

단순 문자열 구현 문제임에도 해결 과정이 꽤 까다로웠습니다.
먼저 문자열을 탐색하면서 현재 인덱스의 문자를 map에 추가합니다.
* 현재 글자가 'I'인 경우
* 패턴 성립 여부 확인 : 조건: 'I'의 개수 == 'O'의 개수 + 1 && 'O'의 개수 >= n.
-> 조건을 만족하면 result++ 증가.
-> 조건을 만족하지 않으면 map을 초기화하고 다시 시작.
* 현재 글자가 'O'인 경우
* 'I'와 'O'의 개수가 맞지 않으면 패턴이 끊어지므로 map 초기화
시간복잡도 : O(n)

[FEAT] #6 이상훈

---

baekjoon/boj_2812_crystal.py

자릿수가 큰 쪽 (왼쪽)일수록 큰 수가 가야 큰 수가 만들어짐을 알고 조건으로 쉽게 생각했다.
이를 통해 자료구조를 통해 빼고 넣고만 잘 하면 되는 문제라고 직감했다.
중간에 제거하는 횟수가 다다르면 더이상 pop하지 않고 나머지 수들을 다 넣는 것으로 생각하고 `len(stack)- cur >= N-K`와 같이 조건문을 복잡하게 구성했음.
이를 cnt로 변환하여 pop할 때마다 -1씩 하는 방식으로 하니 더 직관적이고 쉬워 졌다.
처음엔 deque를 이용하여 빼고 넣었는데, 어차피 한쪽으로만 push, pop을 하는 구조라 stack을 활용해 풀이했다.

[FEAT] #9 최수정

---

baekjoon/boj_17609_crystal.py

- 처음엔 입력되는 string을 `deque` 리스트에 하나씩 담아 앞 뒤로 빼가며 서로 비교해주려고 했음. 
- 그러다가 구현이 복잡해져서 고민하다가 `투포인터`로 해도 이론상은 똑같은 속도로 비교하되 더 쉽게 구현할 수 있음을 느끼고 다시 구현함.
- 시간복잡도 : O(N + N)  => O(N)
- 조건에 따라 3가지 유형의 출력이 있어 분기를 깔끔히 만들기 어려웠음
- 함수와 return을 이용하여 단순하게 표현 
- deque을 활용해야겠다고 생각한 문제에서는 투포인터로 더 쉽게 풀리진 않을까 고민해볼것이다.

[FEAT] #12 최수정

---

baekjoon/boj_3190_crystal.py

제가 push를 처음에 main으로 바로 해버려서, 코드 전문은 변경분이 아니라 파일을 보는 것으로 직접 들어가주셔야 보입니다@
- 들어오는 정보들의 범위가 작아서, 탐색 및 구현으로 푸는 문제라고 생각했습니다.
- 뱀의 움직임을 구현하는 것이 처음에 딱 떠오르지 않았습니다만, 머리로 움직이고 꼬리부터 삭제된다는 점에서 덱을 통해 구현해야 겠다고 생각했습니다.
- 방향을 전환함을 표현하는데 있어서 어려울 수 있습니다. 알고리즘 문제풀이로 다져진 실력으로 생각해냈습니다. ㅋㅋ
```python
dc = [1,0,-1,0] 
dr = [0,1,0,-1]
if command == 'D':
snape_heading = (snape_heading + 1) % 4
else:
snape_heading = (snape_heading - 1) % 4
```

[FEAT] #13 최수정

---

baekjoon/boj_3190_hoon.md

이 문제는 삼성 기출 시뮬레이션 문제로, 주어진 조건에 따라 단계적으로 구현하는 것이 핵심입니다.
저는 Queue와 PriorityQueue 자료구조를 활용하여 문제를 해결했습니다.
* **Queue**
방문한 위치를 나타내기 위해 Pos(x, y) 클래스를 저장합니다.
뱀의 몸을 구성하는 좌표들을 관리하며, 꼬리를 제거하거나 새로운 머리를 추가하는 데 사용됩니다.
* **PriorityQueue**
시간에 따른 방향 전환 정보를 나타내는 Dir(time, dir) 클래스를 저장합니다.
time 기준으로 오름차순 정렬되어, 매 시간마다 방향 전환 여부를 효율적으로 처리할 수 있습니다.

[Feat] #13 이상훈

---

programmers/pgm_92335_hoon.md

진법 변환 결과 문자열을 순차적으로 탐색하며, '0'이 아닌 문자는 누적하고, '0'이 나오면 누적된 문자열을 소수 판별합니다.
[진법 변환]
자바에서는 내장 메서드를 활용하여 간단하게 진법 변환을 할 수 있습니다.
* 10진수를 N진수로 변환: Integer.toString(num, radix)
* N진수를 10진수로 변환: Integer.parseInt(str, radix)
[소수 판별]
효율성을 위해 에라토스테네스의 체를 활용하여 특정 숫자의 제곱근까지만 확인하는 방식으로 성능을 최적화했습니다.
예를 들어, n=1000000, k=2일때 진법 변환 결과는 11110100001001000000(2)와 같이 매우 큰 값이 될 수 있습니다. 이때 소수 판별 과정에서 Integer를 사용하면 오버플로우가 발생할 수 있습니다. 따라서 반드시 long 타입을 사용해야합니다.

[FEAT] #17 이상훈

---

programmers/pgm_92335_crystal.py

- 구현이라고 생각했다.
- 소수 구하는 부분만 큰 숫자에도 빠르게 처리할 수 있도록 고민하면 될 것 이라고 생각했다.
- 처음에 소수를 판별하는 함수를 만들 때, `에라토스 테네의 체` 이용해서 소수 테이블을 만들어서 푸는게 빠를것 이라고 생각했다.
- 어느 숫자까지 탐색해서 테이블의 크기를 만들어야 하는지 기준 세우는게 어려웠다.
- 문제 특성 상 수가 랜덤적이고 0에 따라 자르는 수를 넣어 크기가 크지 않을 것이라 예상하여 그때마다 수의 소수 여부를 진단하는 메서드를 사용하기로 함.
- `0`을 제외하고 숫자를 판별하는 부분에서 `.split()`을 사용하면 쉽게 풀 수 있음
```python
def count_fit_case(num_str_list):
count = 0
tmp_str_num = ''
for i in range(len(num_str_list)):
if num_str_list[i] == '0' and len(tmp_str_num) > 0:
if is_prime(int(tmp_str_num)):
count += 1
tmp_str_num = ''
else:
tmp_str_num += num_str_list[i]
if len(tmp_str_num) > 0:
if is_prime(int(tmp_str_num)):
count += 1
def count_fit_case2(num_str):
count = 0
token_list = num_str.split('0')
for token in token_list:
if token != '' and is_prime(int(token)):
count += 1 …
```

[FEAT] #17 최수정

---

programmers/pgm_17686_hoon.md

문자열 구현 문제입니다.
[문자열 추출]
주어진 각 파일명에 대해 3가지 부분(head, number, tail)을 분리합니다.
head : 첫 번째 숫자가 나오기 전까지 문자들
number : 연속된 숫자들
tail : 그 이후 나머지
</br></br>
[커스텀 정렬 기준 정의]
File 클래스는 각 파일을 나타내는 객체로 idx(파일이 입력된 순서), head, number, tail을 멤버 변수로 갖습니다. 
이를 기반으로 Comparable 인터페이스를 구현하여 커스텀 정렬 기준을 정의합니다.
아래는 우선순위입니다.
1 head : String(사전식) 오름차순 정렬
2 number : Integer(숫자식) 오름차순 정렬
3 idx : 오름차순 정렬

[FEAT] #21 이상훈

---

programmers/pgm_60057_crystal.py

- 주어지는 문자열의 길이가 1_000이하여서, 문자열의 길이를 N으로 봤을 때, O(N^2)의 로직까지 사용할 수 있습니다.
- 따라서 완전탐색 및 구현으로 풀이했습니다.
- 문자열은 제일 앞부터 정해진 길이만큼 잘라야 하므로, 앞에부터 청크 길이만큼 전진만 하면 된단걸 아는것이 포인트 인 것 같습니다.
- 구현하면서 세세한 부분을 신경쓰는게 머리 아팠습니다.

[FEAT] #23 최수정 

---

baekjoon/boj_16234_crystal.py

- 문제의 조건을 이해하고 시뮬레이션 하는데 많은 경우의 수가 떠올라 힘들다.
- 국경일이 열리는 총일을 구하는거라 bfs를 map 단위로 이중 for문과 함께 돌려야 해서 visited 초기화 시점을 생각해내기 까다롭다.
- 해당 문제는 복습하는 것인데, 처음 풀 땐 손도 못 댔었는데 문제를 풀 수 있음에 행복했다,,
- 시간이 오래 걸리는 코드라, 인터넷에 돌아다니는 체스판 기법 사용한 풀이도 숙지되면 좋을 것이다.

[FEAT] #24 최수정

---

programmers/pgm_92341_crystal.py

- 조건에 맞게 구현을 잘 하면 된다고 생각하여 구현으로 풀었습니다.
- 딕셔너리 자료형를 통해 차량에 따른 조건이나 입차/출차를 조회하는데 사용하여 시간을 효율적으로 구성했습니다.
- 글자를 잘라서 조건에 맞게 자료구조를 만드는 것 (파싱)
- 요금을 계산하는 기준을 잘 파악해서 올림하는 것

[FEAT] #27 최수정

---

programmers/pgm_340212_crystal.py

1. limit의 범위가 크기 때문에 최소값을 구하기 위한 그리디한 방법이 있을지 고민함
2. 숙련도를 기준으로 이분탐색으로 하는게 직관적일 것 같아 이분탐색 선택 
- 기준값인 숙련도의 최대값은 문제에서 제시된 diffs 배열에서 난이도가 제일 높은 것으로 설정
- 숙련도의 최대 레벨은 100_000이고 퍼즐 배열의 길이는 300_000이므로 최대 최악의 경우 O(log100_000 * 300_000) 속도로 동작한다. 
- 숙련도가 양의 정수여야 함을 문제 지문에서 놓쳐서 최종 결과가 0으로 나올 때가 있어, 테스트 케이스에 실패했습니다. 
```
return max(1,answer) # 숙련도는 양의 정수여야 한다.
```

[FEAT] #31 최수정

---

programmers/pgm_72411_crystal.py

- 완전탐색, 자료구조, 구현(?)
- 입력되는 데이터의 크기가 작아 조건에 맞게 완전탐색을 잘 구현하면 될 것이라 생각했습니다. 
-  WX, XW 가 다른 코스로 인식 되는 것 ==> 콤비를 우선 정렬해서 저장함으로써 해결 했습니다. 
- 사실 조건에만 충족해야 겠다며 와다다닥 풀었는데 이게 되네? 싶었던 문제입니다 ㅋㅋ 조합때문에 시간 초과가 날 것 같았는데 가지치기를 잘 해줘서 인지 통과했네요
- 푸는데 1시간 걸린건 안 비밀.

[FEAT] #44 최수정

---

programmers/pgm_60057_hoon.md

1~문자열의 길이/2를 단위로 잡고 문자열을 잘라서 비교했습니다.
문자열의 길이가 최대 1000이므로 이중 for문을 사용할 수 있습니다.
자바 String 클래스의 substring() 메서드를 활용해 일정 단위로 문자열을 자릅니다.
자른 문자열이 이전 문자열과 같다면 반복 횟수를 증가시켜 압축합니다.
자른 문자열이 이전 문자열과 다르면 압축을 종료하고 새 문자열로 비교를 시작합니다.
각 단위에 대해 계산된 압축 결과 중 최소값을 반환합니다.
아래 조건을 인지하지 못하여 많은 시간을 소요했습니다 😥
+ 문자열의 첫 글자부터 잘라야 한다는 점, 반복 횟수가 두자리, 세자리인 경우
시간복잡도 : O(n^2)

[FEAT] #23 이상훈

---

baekjoon/boj_12865_hoon.md

널리 알려진 배낭 문제입니다.
점화식은 아래와 같습니다.
```java
dp[i][j] = dp[i-1][j];
if(j-w>=0){
dp[i][j] = Math.max(dp[i][j], dp[i-1][j-w]+v);
}
```
하지만 배낭 문제는 1차원 배열로도 풀 수 있습니다. 1차원 배열로 풀면 메모리를 절약할 수 있습니다. 
이때 중요한 것은 왼쪽->오른쪽이 아닌 오른쪽->왼쪽으로 갱신해야 한다는 것입니다.  아래 블로그를 참고하시길 바랍니다.
https://sskl660.tistory.com/88

[FEAT] #30 이상훈

---

programmers/pgm_340212_hoon.md

숙련도는 1에서 100000까지 가능합니다.
특정 값의 숙련도에서 퍼즐 게임을 푸는데 걸리는 시간은 O(n)이며, 최악의 경우 n = 300000입니다.
따라서 완전 탐색을 진행하면, 100000*300000, 즉 시간 초과가 뜹니다.
어떤 알고리즘을 사용할까 고민하다가, 숙련도의 최솟값을 구하는 문제이므로 파라매트릭 서치(이분탐색)가 생각났습니다.
하한을 1, 상한을 100000, 중간값을 50000으로 설정하고 이분 탐색을 반복적으로 수행하여 조건을 만족하는지 검사합니다.
시간 복잡도 : O(300000*log(100000))

[FEAT] #31 이상훈

---

baekjoon/boj_1027_hoon.md

완전탐색, 수학 관련 문제입니다.
빌딩의 개수 n이 최대 50이므로, 이중 for 문을 활용한 O(n^2) 풀이가 가능합니다.
풀이 과정은 다음과 같습니다.
각 빌딩을 기준으로, 해당 빌딩에서 왼쪽과 오른쪽에서 보이는 빌딩의 개수를 계산합니다.
왼쪽 구간 : 기울기가 최소로 갱신되는 횟수를 계산
오른쪽 구간 : 기울기가 최대로 갱신되는 횟수를 계산
위의 두 값을 더하여 해당 빌딩에서 보이는 빌딩의 개수를 구하고 정답(최대값)을 갱신합니다.
시간 복잡도 : O(n^2) (최대 : 2500)

[FEAT] #37 이상훈

---

baekjoon/boj_1202_hoon.md
baekjoon/boj_15663_hoon.md

dfs를 이용하는 아주 유명한 백트래킹 시리즈 문제입니다. 
set 자료구조를 활용해 중복 순열을 처리해주었습니다.
시간복잡도 : O(n^m)

[FEAT] #48 이상훈

---

baekjoon/boj_1202_crystal.py

- 보석을 고르는 기준이 명확하여 그리디로 풀 수 있을 것이라 예상했습니다.
- 그리디 + 우선순위큐 자료구조 활용
- 입력 개수 범위가 커서 시간초과 굴레에 허덕였습니다.
- 처음엔 visited 리스트를 활용해서 보석과 가방을 이중 for문 돌다가 시간초과가 났음
- 두번째로 가방과 보석의 정렬 기준을 같게 함으로서 보석을 pick하고 Pop하는걸 O(N)으로 이중for문을 이용하지 않아 시간을 줄임
- 그런데도 에러가 떠서 입력을 input() 함수가 아닌 sys readline() 이용해서 해주었더니 되었다.

[FEAT] #46 최수정
